app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required , current_user
from .models import User ,  groups_table , Achievements , Post , IdentifiedPlant , CarePlan
from . import db

auth = Blueprint('auth', __name__)
@auth.route('/scoreboard')
def scoreboard():
    # Fetch all users from the database and order them by identification count in descending order
    users = User.query.order_by(User.identification_count.desc()).all()
    
    # Render the scoreboard template with the users data
    return render_template('scoreboard.html', users=users)
@auth.route('/achievements')
@login_required
def achievements():
    all_achievements = Achievements.query.all()
    user_achievements = current_user.achievements

    # Check achievements based on identification count
    identification_count = current_user.identification_count

    beginner_achievement = check_achievement(current_user, "Beginner", 5)
    intermediate_achievement = check_achievement(current_user, "Intermediate", 10)
    advanced_achievement = check_achievement(current_user, "Advanced", 15)
    expert_achievement = check_achievement(current_user, "Expert", 20)
    master_achievement = check_achievement(current_user, "Master", 25)

    return render_template('achievements.html', all_achievements=all_achievements, user_achievements=user_achievements)

@auth.route("/profile")
def profile():
    return render_template("profile-page.html")

@auth.route("/discover")
def discover():
    return render_template("discover-page.html")

@auth.route("/search")
def search():
    return render_template("Search-Groups.html")

@auth.route('/groups', methods=['GET', 'POST'])
@login_required
def view_groups():
    if request.method == 'POST':
        group_id = request.form.get('group_id')
        group = groups_table.query.get(group_id)

        if group:
            if current_user in group.users:
                flash('You are already a member of this group.')
            else:
                group.users.append(current_user)
                db.session.commit()
                flash('You have joined the group successfully.')
        else:
            flash('Group does not exist.')

    groups = groups_table.query.all()
    return render_template('Groups-view.html', groups=groups)

@auth.route('/groups/create', methods=['GET', 'POST'])
@login_required
def create_group():
    if request.method == 'POST':

        group_name = request.form['group-name']
        description = request.form['group-description']
        country = request.form['select-country']

        new_group = groups_table(group_name=group_name, description=description , country = country)
        new_group.users.append(current_user)

        db.session.add(new_group)
        db.session.commit()
        
        
        newly_created_group_id = new_group.id
        
        #return redirect(url_for('group_details', group_id=newly_created_group_id))
        return redirect(url_for('main.profile'))
    
    
    return render_template('Groups-create.html')

@auth.route('/groups/<int:group_id>')
@login_required
def group_profile(group_id):
    group = groups_table.query.get(group_id)

    #if not group:
        #abort(404)

    if current_user not in group.users:
        flash("You are not a member of this group.")
        return redirect(url_for('auth.view_groups'))

    posts = Post.query.filter_by(group_id=group_id).all()

    return render_template('group_profile.html', group=group, posts=posts)

@auth.route('/create_post/<int:group_id>', methods=['POST'])
@login_required
def create_post(group_id):
    content = request.form.get('content')
    group = groups_table.query.get(group_id)
    
    if content:
        post = Post(content=content, group_id=group_id, user_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Post created successfully.', 'success')
    else:
        flash('Post content cannot be empty.', 'danger')
    
    return redirect(url_for('auth.group_profile', group_id=group_id))


@auth.route('/profile/myplants')
@login_required
def my_plants():
    user_plants = IdentifiedPlant.query.filter_by(user_id=current_user.id).all()
    return render_template('my_plants.html', user_plants=user_plants)

@auth.route('/profile/myplants/<int:plant_id>')
@login_required
def my_plant_details(plant_id):
    plant = IdentifiedPlant.query.get(plant_id)
    
    if not plant or plant.user_id != current_user.id:
        #flash('Plant not found.', 'error')
        return redirect(url_for('auth.my_plants'))
    
    return render_template('my_plant_details.html', plant=plant)


@auth.route('/profile/myplants/<int:plant_id>/add-care-plan', methods=['GET', 'POST'])
@login_required
def add_care_plan(plant_id):
    plant = IdentifiedPlant.query.get(plant_id)

    if not plant or plant.user_id != current_user.id:
        flash('Plant not found.')
        return redirect(url_for('auth.my_plants'))

    if request.method == 'POST':
        plan_name = request.form.get('plan_name')
        light = request.form.get('light')
        last_watered = request.form.get('last_watered')
        pot_height = float(request.form.get('pot_height'))
        pot_diameter = float(request.form.get('pot_diameter'))

        water_amount = 0
        fertilize_interval = ""

        # Calculate water amount based on light type
        if light == 'option1':
            water_amount = 30
        elif light == 'option2':
            water_amount = 20
        elif light == 'option3':
            water_amount = 10
        elif light == 'option4':
            water_amount = 5

        # Calculate fertilize interval based on pot size
        pot_size = pot_height * pot_diameter
        if pot_size > 100:
            fertilize_interval = "every month"
        elif 50 <= pot_size <= 100:
            fertilize_interval = "every week"
        elif pot_size < 50:
            fertilize_interval = "every 2 days"

        # Create and store the care plan in the database
        care_plan = CarePlan(plant_id=plant.id, water_amount=water_amount, fertilize_interval=fertilize_interval, plan_name=plan_name)
        db.session.add(care_plan)
        db.session.commit()

        flash('Care plan added successfully.', 'success')
        return redirect(url_for('auth.my_plant_details', plant_id=plant_id))

    return render_template('Smart_Care.html', plant=plant)



@auth.route("/identification")
def identification():
    return render_template("identification-page.html")

@auth.route("/register")
def register():
    return render_template("register-page.html")

@auth.route('/login')
def login():
    return render_template('login-page.html')

@auth.route('/login', methods=['POST'])
def login_post():
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))

@auth.route('/signup')
def signup():
    return render_template('register-page.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')
    confirm_password = request.form.get("confirm-password")

    user = User.query.filter_by(email=email).first()

    if user:
        flash('Email address already exists.')
        return redirect(url_for('auth.register'))
    
    if password != confirm_password:
       flash("Confirmation password does not mactch with password.")
       return redirect(url_for('auth.register'))
    
    new_user = User(email=email, name=name, password=generate_password_hash(password))

    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

def check_achievement(user, achievement_name, identification_count_threshold):
    if user.identification_count >= identification_count_threshold:
        achievement = Achievements.query.filter_by(name=achievement_name).first()
        if achievement not in user.achievements:
            user.achievements.append(achievement)
            db.session.commit()
            return True
    return False


app/main.py
from flask import Blueprint, render_template
from flask_login import login_required
from flask_login import login_required, current_user

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main-page.html')

@main.route('/profile')
@login_required
def profile():
    return render_template('profile-page.html', name=current_user.name)

@main.route('/discover')
def discover():
    return render_template('discover-page.html')

app/views.py
from datetime import datetime
from flask import Blueprint, render_template, request, current_app
from flask_login import current_user
from keras.preprocessing.image import load_img, img_to_array
from keras.models import load_model
import numpy as np
import os
from .models import User , db , IdentifiedPlant

views = Blueprint('views', __name__)

@views.route('/classification')
def classification():
    return render_template('identification-page.html')


@views.route('/predict', methods=['POST'])
def predict():
    if request.method == 'POST':
        # Gelen görüntüyü kaydet
        image_file = request.files['image']
        if image_file:
            image_path = os.path.join(current_app.config['UPLOAD_FOLDER'], image_file.filename)
            print("IMAGE PATH IS AS FOLLOWS!!:", image_path)
            image_file.save(image_path)

            # Görüntüyü yükle ve yeniden boyutlandır
            img = load_img(image_path, target_size=(224, 224))
            img_array = img_to_array(img)
            img_array = np.expand_dims(img_array, axis=0)

            # Modeli yükle
            model_path = os.path.join(current_app.root_path, 'modelVersion1.h5')
            model = load_model(model_path)

            class_names = ['Daisy!', 'Dandelion!', 'Rose!', 'Sunflower!']



            # Tahmin yap
            prediction = model.predict(img_array)
            predicted_class = class_names[np.argmax(prediction)]
            global x
            if predicted_class == 'Daisy!':
                    photo = 'static/daisy.jpeg'
                    x=1
            elif predicted_class == 'Dandelion!':
                    photo = 'static/dandelion.jpeg'
                    x=2
            elif predicted_class == 'Rose!':
                    photo = 'static/rose.jpeg'
                    x=3
            elif predicted_class == 'Sunflower!':
                    photo = 'static/sunflower.jpeg'
                    x=4
            
            #for achievements
            if current_user.is_authenticated:
                user = User.query.get(current_user.id)
                if user:
                    user.identification_count += 1
                    db.session.commit()
             # Store identified plant in the database
            if current_user.is_authenticated:
                user = User.query.get(current_user.id)
                if user:
                    identified_plant = IdentifiedPlant(user_id=user.id, plant_name=predicted_class, date_identified=datetime.utcnow())
                    db.session.add(identified_plant)
                    db.session.commit()


            return render_template('prediction_results.html', photo=photo, predicted_class=predicted_class)

@views.route('/Info')
def Info():
    if x == 1:
        return render_template('Daisy_Info.html')
    elif x == 2:
        return render_template('Dandelion_Info.html')
    elif x == 3:
        return render_template('Rose_Info.html')
    elif x == 4:
        return render_template('Sunflower_Info.html')

app/templates/Daisy_Info.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
  rel="stylesheet"
  href="{{ url_for('static', filename='/Info.css') }}"
/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <title>Herbify-Additional Information</title>
</head>
<body>
  <nav class="navbar">
    <ul>
    <div class="container">

        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">

                <li><a href="{{ url_for('main.index') }}" class="navbar-item" title="main">🏠</a></li>

                <!-- <li><a href="{{ url_for('main.discover')}}" title="Discover" class="navbar-item">🌐</a></li> -->

                <li><a href="{{ url_for('views.classification')}}" class="navbar-item" title="Classification">🔍</a></li>

                {% if current_user.is_authenticated %}
                <li>
                  <a href="{{ url_for('main.profile') }}" title="Profile">👤</a></li>
                {% endif %}

                <li><a href= "{{ url_for('auth.view_groups') }}" title="Groups" class="navbar-item">👥</a></li>
                <li><a href="{{ url_for('auth.achievements') }}" title="Rank" class="navbar-item">🏆</a></li>

                {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}" class="navbar-item" title="login">🔒</a></li>

                <li><a href="{{ url_for('auth.signup') }}" class="navbar-item" title="signup">🔓</a></li>


                {% endif %}
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}" class="navbar-item" title="logout">🚪</a></li>
                {% endif %}


            </div>
        </div>
    </div>
    <ul>
</nav>
  <div class="register-page-container">
    <h1 class="register-page-heading">Daisy</h1>
    <h2 class="subheader">Origin and Geographic Distribution</h2>
    <div class="subheader-container">
      <!-- Explanation for Origin and Geographic Distribution -->
   Daisy flowers are vibrant, cheerful, and easy to grow, making them a proven choice for gardens. Stunning, reliable bloomers, both in the garden and as cut flowers, daisies are hardy, drought-tolerant plants that provide years of gorgeous, classic charm.
This star-shaped flowering plant can be either annual or a perennial and comes in a variety of colors from bright white to the most electrifying shades of pinks, purples, and yellows. These low-maintenance, iconic garden plants of Summer, will reward you with endless blooms throughout the summer and well into the Fall. 
    </div>
    <h2 class="subheader">Growth and Development</h2>
    <div class="subheader-container">
      <!-- Explanation for Growth and Development -->
   Daisies prefer rich fast-draining soil, plenty of water, and ample sunshine. Healthy soil means healthy roots for your daisies, so it’s best to put the time in to amend the soil in your garden before planting. Use a mix of organic matter, including sand, peat moss, and manure compost, to create an ideal growing environment for strong plants with showy blooms. Daisies thrive in soil that is neutral to slightly acidic ideally, with soil measuring 6.0-8.0 on the pH scale. Water daisy plants during dry spells as they send up flower buds as well as during their entire blooming time. If flower stems dry out and droop, they might not fully recover. Water daisies amply at the base of the plant to avoid mold and sun damage to tender petals. Apply an all-purpose organic fertilizer early in the season to promote strong, sturdy growth. Trim off blooms as they fade. Deadheading these blooming beauties encourages repeated flowering. Removing spent flowers also minimizes mold growth on decaying flowers.
Keep root systems from getting too big and overcrowding each other, which will lead to a decline in the daisy plant over time. As daisy plants get very large, dig them up in clumps every other year in the Fall. Divide the root balls with a slice from a sturdy garden shovel and cut away the thick woody center. Then replant the separated plants with a spacing of 10-12 inches per section.
Prepare perennial daisies for winter by cushioning mulch loosely around each daisy plant. Use extra taking not to cover the leaves.
    </div>
    <h2 class="subheader">Propagation and Planting</h2>
    <div class="subheader-container">
      <!-- Explanation for Propagation and Planting -->
          Daisies, just like their cheerful appearance would suggest, are sun-loving plants. Plant them in full sun for the best and most rewarding blooms all season long. Perennial daisies are easy to grow from seed, root division, or plants purchased from your local nursery. They are also great to separate at the root ball to share your artful bloomers with friends and neighbors.
Grow from seed: Plant your daisy seeds early Spring. Seeds can be sown directly into the garden or started in covered seed containers indoors. Plant your seeds in the soil about 1/8 inch deep. You can expect them to germinate in 10-20 days. Daisy plants will bloom the following year after one season’s growth.
Planting rooted plants: Dig a hole that is twice the diameter of the pot in came in. Then place the plant in the hole, using care to ensure that the top of the root ball is flush with the surface of the soil. Loosely fill in the rest of the hole
    </div>
  </div>
</body>
</html>


app/templates/Groups-view.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />

  <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/Groups-view.css') }}"
    />
  <title>Herbify - Create Group</title>
</head>
<body>
  <nav class="navbar">
    
    <ul>
    <div class="container">
     
        <div id="navbarMenuHeroA" class="navbar-menu">
          
            <div class="navbar-end">

                <li ><a href="{{ url_for('main.index') }}" class="navbar-item" title="main">🏠</a></li>

                <!-- <li><a href="{{ url_for('main.discover')}}" title="Discover" class="navbar-item">🌐</a></li> -->

                <li><a href="{{ url_for('views.classification')}}" class="navbar-item" title="Classification">🔍</a></li>

                {% if current_user.is_authenticated %}
                <li>
                  <a href="{{ url_for('main.profile') }}" title="Profile">👤</a></li>
                {% endif %}

                <li class="active"><a href= "{{ url_for('auth.view_groups') }}" title="Groups" class="navbar-item">👥</a></li>
                <li><a href="{{ url_for('auth.achievements') }}" title="Rank" class="navbar-item">🏆</a></li>

                {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}" class="navbar-item" title="login">🔒</a></li>

                <li><a href="{{ url_for('auth.signup') }}" class="navbar-item" title="signup" >🔓</a></li>


                {% endif %}
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}" class="navbar-item" title="logout">🚪</a></li>
                {% endif %}


            </div>
        </div>
    </div>
    <ul>
</nav>
  <div class="login-page-container">
    <h1 class="login-page-heading">Groups of the Herbify</h1>

    <div class="button-group">
      <a href="{{ url_for('auth.create_group') }}"
          ><button type="submit" class="login-page-button">
            Create Group
          </button></a
        >
    </div>
    <div class="group-names-container">
      <!-- Flash Messages -->
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        <div class="flash-messages">
        {% for message in messages %}
          <div class="flash-message">{{ message }}</div>
        {% endfor %}
        </div>
      {% endif %}
      {% endwith %}
        <ul>
      {% for group in groups %}
        <li>
          <a href="{{ url_for('auth.group_profile', group_id=group.id) }}">{{ group.group_name }}</a>
        </li>
        <form action="{{ url_for('auth.view_groups') }}" method="POST">
          <input type="hidden" name="group_id" value="{{ group.id }}">
          <button type="submit" class="login-page-button">Join Group</button>
        </form>
      {% endfor %}
    </ul>
      </div>
    </div>
  </body>
  </html>
  

app/templates/Smart_Care.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link  href="{{ url_for('static', filename='/Smart_Care.css') }}" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <title>Smart Care</title>
</head>
<body>
  <nav class="navbar">
    <ul>
    <div class="container">

        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">

                <li><a href="{{ url_for('main.index') }}" class="navbar-item" title="main">🏠</a></li>

                <!-- <li><a href="{{ url_for('main.discover')}}" title="Discover" class="navbar-item">🌐</a></li> -->

                <li class="active"><a href="{{ url_for('views.classification')}}" class="navbar-item" title="Classification">🔍</a></li>

                {% if current_user.is_authenticated %}
                <li>
                  <a href="{{ url_for('main.profile') }}" title="Profile">👤</a></li>
                {% endif %}

                <li><a href= "{{ url_for('auth.view_groups') }}" title="Groups" class="navbar-item">👥</a></li>
                <li><a href="{{ url_for('auth.achievements') }}" title="Achievements" class="navbar-item">🏆</a></li>

                {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}" class="navbar-item" title="login">🔒</a></li>

                <li><a href="{{ url_for('auth.signup') }}" class="navbar-item" title="signup" >🔓</a></li>


                {% endif %}
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}" class="navbar-item" title="logout">🚪</a></li>
                {% endif %}


            </div>
        </div>
    </div>
    <ul>
</nav>
  <div class="register-page-container">
    <h1 class="register-page-heading">Add a Care Plan</h1>
    <form class="register-page-form" name="smart_care_form" method="POST" action="">
      <label for="plan_name">Give a Plant Name</label>
      <input type="text" id="plan_name" name="plan_name" required>

      <label for="light">What kind of light does your plant get daily?</label>
      <select id="light" name="light" required>
        <option value="" disabled selected>Select type</option>
        <option value="option4">Low light</option>
        <option value="option3">Medium light</option>
        <option value="option2">Bright indirect light</option>
        <option value="option1">Bright direct light</option>
      </select>
      
      <label for="last_watered">When did you last water your plant?</label>
      <select id="last_watered" name="last_watered" required>
        <option value="" disabled selected>Select watering time</option>
        <option value="option1">Today</option>
        <option value="option2">Yesterday</option>
        <option value="option3">A week ago</option>
        <option value="option4">Over a month ago</option>
      </select>

      <label for="pot_height">Pick the height of the pot (in cm)</label>
      <input type="number" id="pot_height" name="pot_height" required min="0">

      <label for="pot_diameter">Pick the bottom diameter of the pot (in cm)</label>
      <input type="number" id="pot_diameter" name="pot_diameter" required min="0">

      <button type="submit" class="register-page-button">Add Care plan</button>
    </form>
  </div>
</body>
</html>

app/templates/achievements.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{{ url_for('static', filename='/Achievements.css') }}" rel="stylesheet" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
  <title>Achievements</title>
</head>
<body>
  <nav class="navbar">
    <ul>
    <div class="container">

        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">

                <li><a href="{{ url_for('main.index') }}" class="navbar-item" title="main">🏠</a></li>

                <!-- <li><a href="{{ url_for('main.discover')}}" title="Discover" class="navbar-item">🌐</a></li> -->

                <li class="active"><a href="{{ url_for('views.classification')}}" class="navbar-item" title="Classification">🔍</a></li>

                {% if current_user.is_authenticated %}
                <li>
                  <a href="{{ url_for('main.profile') }}" title="Profile">👤</a></li>
                {% endif %}

                <li><a href= "{{ url_for('auth.view_groups') }}" title="Groups" class="navbar-item">👥</a></li>
                <li><a href="{{ url_for('auth.achievements') }}" title="Achievements" class="navbar-item">🏆</a></li>

                {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}" class="navbar-item" title="login">🔒</a></li>

                <li><a href="{{ url_for('auth.signup') }}" class="navbar-item" title="signup" >🔓</a></li>


                {% endif %}
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}" class="navbar-item" title="logout">🚪</a></li>
                {% endif %}


            </div>
        </div>
    </div>
    <ul>
</nav>

  <div class="register-page-container">
    <h1 class="register-page-heading">Achievements</h1>
    <div class="achievements-container">
      <!-- Add elements from Flask dynamically here -->
        {% for achievement in all_achievements %}
                  <div class="achievement">
                      <img src="{{ url_for('static', filename='ach_images/achiv.jpg') }}" alt="Achievement Image">
                      <div class="achievement-title">{{ achievement.name }}</div>
                      &emsp;&emsp;<div class="achievement-description">{{ achievement.description }}</div>
                      {% if achievement in user_achievements %}
                          <div class="achievement-achieved">Congratulations! You achieved this!</div>
                      {% endif %}
                  </div>
              {% endfor %}
    </div>
    <a href="{{ url_for('auth.scoreboard') }}" class="go-to-scores-button">Go to Scores</a>
  </div>
</body>
</html>

app/templates/prediction_results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='/identification-page.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <title>Herbify-Identification</title>
  </head>
  <body>
    <script>
      document
        .querySelector('a[href="register-page.html"]')
        .addEventListener("click", function (event) {
          event.preventDefault();
          window.location.href = "register-page.html";
        });

      document
        .querySelector('a[href="login-page.html"]')
        .addEventListener("click", function (event) {
          event.preventDefault();
          window.location.href = "login-page.html";
        });

      document
        .querySelector('a[href="identification-page.html"]')
        .addEventListener("click", function (event) {
          event.preventDefault();
          window.location.href = "identification-page.html";
        });
    </script>
   <nav class="navbar">
    <ul>
    <div class="container">

        <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">

                <li><a href="{{ url_for('main.index') }}" class="navbar-item" title="main">🏠</a></li>

                <!-- <li><a href="{{ url_for('main.discover')}}" title="Discover" class="navbar-item">🌐</a></li> -->

                <li><a href="{{ url_for('views.classification')}}" class="navbar-item" title="Classification">🔍</a></li>

                {% if current_user.is_authenticated %}
                <li>
                  <a href="{{ url_for('main.profile') }}" title="Profile">👤</a></li>
                {% endif %}

                <li><a href= "{{ url_for('auth.view_groups') }}" title="Groups" class="navbar-item">👥</a></li>
                <li><a href="{{ url_for('auth.achievements') }}" title="Rank" class="navbar-item">🏆</a></li>

                {% if not current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.login') }}" class="navbar-item" title="login">🔒</a></li>

                <li><a href="{{ url_for('auth.signup') }}" class="navbar-item" title="signup">🔓</a></li>


                {% endif %}
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('auth.logout') }}" class="navbar-item" title="logout">🚪</a></li>
                {% endif %}


            </div>
        </div>
    </div>
    <ul>
</nav>
    <div class="identification-page-container">

      <div class="upload-photo-container">
        <p class="upload-photo-text">Prediction Done</p>
        
        
        <img
          src="{{photo}}"
          alt="predict"
          width="300" height="200"
          position="absolute"
          top="30px"
          left="300px"

        />
        
        <p class="upload-photo-text">Prediction Result: {{ predicted_class }} </p>

        <a href="{{ url_for('views.Info') }}"
          ><button type="submit" class="upload-photo-button">
            More Information
          </button></a
        >
        <a href="{{ url_for('views.classification') }}"
          ><button type="submit" class="upload-photo-button">
            Identify Another Plant
          </button></a
        >

      </div>
    </div>
  </body>
</html>